StenaDotNet/Controllers/WallController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace StenaDotNet.Controllers
{
    public class WallController : Controller
    {
        // GET: Wall
        public ActionResult Index()
        {
            return View();
        }
    }
}

StenaDotNet/Views/Shared/_Header.cshtml
@using StenaResources

<div class="navbar navbar-default navbar-fixed-top">
    <div class="container">
        <div class="navbar-header navbar-header-fix">
            <button type="button" aria-controls="navbar" data-toggle="collapse" data-target="#navbar"
                    aria-expanded="false" class="navbar-toggle collapsed">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a href='@Url.Action("Index", "Home", new { area = "" })' class="navbar-brand stena-brand">
                <span class="blue">STENA</span>
                <span>NET</span>
            </a>
        </div>
        <div class="navbar-collapse collapse" id="navbar">
            <ul class="nav navbar-nav">
                <li>@Html.ActionLink(Navigation.About, "Index", "Home")</li>
                <li>@Html.ActionLink(Navigation.OurPartners, "Partners", "Home")</li>
                <li>@Html.ActionLink(Navigation.HowItWorks, "HowItWorks", "Home")</li>
                <li>@Html.ActionLink(Navigation.AllWalls, "Index", "Wall")</li>
            </ul>
            @*Html.Partial("_LoginPartial")*@
        </div>
    </div>
</div>

StenaDotNet/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta lang="en"/>
    <meta http-equiv="X-UA-Compatible" content="IE=edge"/>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    @RenderSection("meta", false)
    <link rel="icon" type="image/x-icon" href="@Url.Content("~/favicon.ico")">
    <title>@ViewBag.Title - StenaNet</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    @Html.Partial("_Header")
    <div class="container body-content">
        @RenderBody()
    </div>

    <footer class="our-footer">
        <div class="container">
            <span>version @ViewBag.Version</span>
            <span style="display:none">&copy; @DateTime.Now.Year - Denis Krasakov</span>
        </div>
    </footer>
    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>