StenaDotNet/Areas/Admin/Controllers/AdminController.cs
using AutoMapper;
using Services;
using StenaDotNet.Areas.Admin.Models.Admin;
using System.Web.Mvc;

namespace StenaDotNet.Areas.Admin.Controllers
{
    [Authorize(Roles = "admin")]
    public class AdminController : Controller
    {
        private readonly WallService _wallService;


        public AdminController(WallService wallService)
        {
            _wallService = wallService;
        }

        // GET: Admin/Admin
        public ActionResult Index()
        {
            var sumDto = _wallService.GetSummary();

            var summary = Mapper.Map<SummaryModel>(sumDto);
            return View(summary);
        }
    }
}

StenaDotNet/Areas/Admin/Controllers/WallContentController.cs
using AutoMapper;
using Services;
using Services.DTO.Walls;
using Services.Utility;
using Services.Walls;
using StenaDotNet.Areas.Admin.Models.WallContent;
using System.Collections.Generic;
using System.IO;
using System.Threading;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;

namespace StenaDotNet.Areas.Admin.Controllers
{
    [Authorize(Roles="admin")]
    public class WallContentController : Controller
    {
        private readonly WallService _wallService;
        private readonly WallCrudService _wallCrudService;
        private readonly IFileUploadService _fileUploadService;

        public WallContentController(WallService wallService, WallCrudService wallCrudService, 
            IFileUploadService fileUploadService)
        {
            _wallService = wallService;
            _wallCrudService = wallCrudService;
            _fileUploadService = fileUploadService;
        }

        // GET: Admin/WallContent
        public ActionResult Index()
        {
            var model = new WallListModel();

            model.ViewList = _wallCrudService.GetList();

            return View(model);
        }

        [HttpGet]
        public ActionResult AddEditWall(int? id)
        {
            if (id.HasValue)
            {
                var model = _wallCrudService.ViewWall(id.Value);
                if (model != null)
                {

                    var resultModel = Mapper.Map<WallModel>(model);

                    resultModel.Content = new List<WallContentModel>
                    {
                        new WallContentModel
                        {
                            ContentId = 1,
                            Name = "content1"
                        },

                        new WallContentModel
                        {
                            ContentId = 1,
                            Name = "content2"
                        }
                    };
                    return View("AddEditWall", resultModel);
                }
            }
            return View("AddEditWall", new WallModel());
        }
        
        [HttpPost]
        public JsonResult AddEditWall(WallModel wall)
        {
            if (ModelState.IsValid)
            {
                var editModel = Mapper.Map<EditWallDto>(wall);
                var result = _wallCrudService.CreateUpdateWall(editModel);
                //todo: better to change client location, not this
                var redirectUrl = wall.WallId == 0 ? Url.Action("AddEditWall", new { id = result.WallId}) : null;                
                return Json(new { success = true, redirect = redirectUrl });
            }

            return Json(new { success = false, reason = "Validation!"});
        }

        [HttpPost]
        public async Task<JsonResult> UploadImage(HttpPostedFileBase file)
        {
            var url = await _fileUploadService.UploadFileAndGetUrl(file.InputStream, file.FileName);
            return Json(new { success = true , url = url});
        }

    }
}

StenaDotNet/Areas/Admin/Views/Shared/_Layout.cshtml
@using StenaResources

<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="icon" type="image/x-icon" href="@Url.Content("~/favicon.ico")">
    <title>@ViewBag.Title - StenaNet Admin</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body ng-app="app">
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("STENANET", "Index", "Admin", new { area = "Admin" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink(Admin.ManageContent, "Index", "WallContent")</li>
                </ul>
            </div>
        </div>
    </div>

    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>
                <span>@Common.Version @ViewBag.Version</span>&nbsp;&copy; @DateTime.Now.Year - Denis Krasakov
            </p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/angular")
    @Scripts.Render("~/bundles/bootstrap")
    @Scripts.Render("~/bundles/customAdmin")
    @RenderSection("scripts", required: false)
</body>
</html>